language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJWCD22OJHLYTH23Q
  secret_access_key:
    secure: r/+NSkBZuWcbPKGvyGo6NvI8jgIp3Fa5+M9QQ4FDtW/3DoHej4xgCVXJouLkQJrulgju/RLeyDtVnWLm/Qj53cBJGnTTJcuH6JM2sq37ujYbhr8AKJJHHzOfNzoK68dryzsekw2L5JSTclTwBcrCnp6ZM472YSwu4V4lk06VluQw+OoLA6mQ85NG8kOggRJBVReXdQOkByPXHeb5SFwJW8N2Q2HtI60mwt0bL1cUNI5xP9NjNb08j02bdayIw0Rfvr3XyXSrbXhi85kKF39rBFd+dHGVo0S3ZeFubpNgYuIr3xhrKkA1Bpeaairef3yARN1zRNjxRl93wQ2Wr942rZavJg43KOewKWQUjDADrYn/X188vznsUPaE4g8GGH3JGYTJ5isJD245RcRKApjNvw6Qn0rLr9UV4QmdgBO+OfMSCXToWpgo3G1bkRAxJF1wT/+H3UrFKQom7iz1e2VFUMfzctE6iad8E3BRY+akziQYsJoLLFocH0trCrO7ZCgp0VCTAFfdBnqTvlPHrkUEm9Za/89czuXzE1UEOC4BdkTYnMRmkiuKh/yXPoSuVtEbj/+G9LBZMqOF9ctO2Zvb04mF2rjaSN+3ltruxZ1GH2B2uKZEpXzyLasPK4iN/eVKma3DZOTA6Z+o/fE/3urZMv9Ur4EWPUSlZ2cugF/mlJQ=
  bucket: celebrity-hospital.com
  acl: private
  on:
    repo: leggomuhgreggo/celeb
